# Generated by Django 5.1.4 on 2025-09-22 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('EN_COURS', 'En cours'), ('EXPIREE', 'Expirée'), ('ATTENTE', 'En attente')], default='ATTENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion')], max_length=20)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hotspot.usersession')),
            ],
        ),
    ]
